apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
    purpose: helm
  ports:
  - protocol: TCP
    port: 80 #service-port
    #targetPort: 8080 #target-port
    targetPort: {{ .Values.configmap.port }}
    nodePort: {{ .Values.serivce.nodePort }}
